### Authorization by token, part 1. Retrieve and save token.
POST http://localhost:8080/auth/realms/beans/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}&client_secret={{client_secret}}&grant_type=password&username=reader-user&password=test

> {% client.global.set("client_auth_token", response.body.access_token); %}

###
GET http://localhost:9090/api/1/resource/
Accept: application/json
Authorization: Bearer {{client_auth_token}}

